-- Permet d’importer les id SQLite tout en gardant les séquences cohérentes (script scripts/sqlite-to-supabase.mjs).

ALTER TABLE IF EXISTS public.realisations
  ALTER COLUMN id SET GENERATED BY DEFAULT;

ALTER TABLE IF EXISTS public.opportunity_posts
  ALTER COLUMN id SET GENERATED BY DEFAULT;

ALTER TABLE IF EXISTS public.opportunity_post_history
  ALTER COLUMN id SET GENERATED BY DEFAULT;

ALTER TABLE IF EXISTS public.opportunity_feed_subscribers
  ALTER COLUMN id SET GENERATED BY DEFAULT;
