-- ============================================================================
-- Orbis Publica — Migration Supabase (PostgreSQL)
-- Tables, index, RLS, fonctions RPC
-- ============================================================================

-- ==================== TABLES ====================

CREATE TABLE IF NOT EXISTS public.realisations (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title       TEXT NOT NULL,
  description TEXT NOT NULL,
  category    TEXT NOT NULL,
  image       TEXT NOT NULL,
  published   BOOLEAN NOT NULL DEFAULT false,
  sort_order  INTEGER NOT NULL DEFAULT 0,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.service_publications (
  slug         TEXT PRIMARY KEY,
  published    BOOLEAN NOT NULL DEFAULT true,
  sort_order   INTEGER NOT NULL DEFAULT 0,
  content_json TEXT,
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.site_settings (
  key        TEXT PRIMARY KEY,
  value_json TEXT NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.opportunity_posts (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category              TEXT NOT NULL,
  title                 TEXT NOT NULL,
  summary               TEXT NOT NULL DEFAULT '',
  body                  TEXT NOT NULL DEFAULT '',
  link_url              TEXT,
  image_url             TEXT,
  attachments_json      TEXT,
  consultation_deadline TEXT,
  organisme             TEXT,
  lieu                  TEXT,
  status                TEXT NOT NULL DEFAULT 'draft',
  scheduled_for         TIMESTAMPTZ,
  published_at          TIMESTAMPTZ,
  sort_order            INTEGER NOT NULL DEFAULT 0,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.opportunity_post_history (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id     BIGINT,
  event_type  TEXT NOT NULL,
  detail_json TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.opportunity_feed_subscribers (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category   TEXT NOT NULL,
  email      TEXT NOT NULL,
  name       TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (email, category)
);

-- Table admin : contient les user_id (Auth) autorisés
CREATE TABLE IF NOT EXISTS public.site_admins (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ==================== INDEX ====================

CREATE INDEX IF NOT EXISTS idx_opp_posts_cat_status
  ON public.opportunity_posts (category, status, sort_order);

CREATE INDEX IF NOT EXISTS idx_opp_posts_scheduled
  ON public.opportunity_posts (status, scheduled_for);

CREATE INDEX IF NOT EXISTS idx_opp_history_created
  ON public.opportunity_post_history (created_at);

CREATE INDEX IF NOT EXISTS idx_opp_feed_sub_cat
  ON public.opportunity_feed_subscribers (category, created_at DESC);

-- ==================== RLS ====================

ALTER TABLE public.realisations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.service_publications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.opportunity_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.opportunity_post_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.opportunity_feed_subscribers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.site_admins ENABLE ROW LEVEL SECURITY;

-- Helper: est-ce un admin ?
CREATE OR REPLACE FUNCTION public.is_site_admin()
RETURNS BOOLEAN
LANGUAGE sql
SECURITY DEFINER
STABLE
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.site_admins WHERE user_id = auth.uid()
  );
$$;

-- ----- realisations -----
DROP POLICY IF EXISTS "realisations_public_read" ON public.realisations;
CREATE POLICY "realisations_public_read" ON public.realisations
  FOR SELECT USING (published = true);

DROP POLICY IF EXISTS "realisations_admin_all" ON public.realisations;
CREATE POLICY "realisations_admin_all" ON public.realisations
  FOR ALL USING (public.is_site_admin());

-- ----- service_publications -----
DROP POLICY IF EXISTS "sp_public_read" ON public.service_publications;
CREATE POLICY "sp_public_read" ON public.service_publications
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "sp_admin_all" ON public.service_publications;
CREATE POLICY "sp_admin_all" ON public.service_publications
  FOR ALL USING (public.is_site_admin());

-- ----- site_settings -----
DROP POLICY IF EXISTS "ss_public_read" ON public.site_settings;
CREATE POLICY "ss_public_read" ON public.site_settings
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "ss_admin_all" ON public.site_settings;
CREATE POLICY "ss_admin_all" ON public.site_settings
  FOR ALL USING (public.is_site_admin());

-- ----- opportunity_posts -----
DROP POLICY IF EXISTS "opp_public_read" ON public.opportunity_posts;
CREATE POLICY "opp_public_read" ON public.opportunity_posts
  FOR SELECT USING (status = 'published');

DROP POLICY IF EXISTS "opp_admin_all" ON public.opportunity_posts;
CREATE POLICY "opp_admin_all" ON public.opportunity_posts
  FOR ALL USING (public.is_site_admin());

-- ----- opportunity_post_history -----
DROP POLICY IF EXISTS "oph_admin_all" ON public.opportunity_post_history;
CREATE POLICY "oph_admin_all" ON public.opportunity_post_history
  FOR ALL USING (public.is_site_admin());

-- Permettre insert pour tout utilisateur authentifié (logging interne)
DROP POLICY IF EXISTS "oph_insert_authenticated" ON public.opportunity_post_history;
CREATE POLICY "oph_insert_authenticated" ON public.opportunity_post_history
  FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "oph_select_authenticated" ON public.opportunity_post_history;
CREATE POLICY "oph_select_authenticated" ON public.opportunity_post_history
  FOR SELECT USING (auth.uid() IS NOT NULL);

-- ----- opportunity_feed_subscribers -----
DROP POLICY IF EXISTS "ofs_public_insert" ON public.opportunity_feed_subscribers;
CREATE POLICY "ofs_public_insert" ON public.opportunity_feed_subscribers
  FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "ofs_admin_all" ON public.opportunity_feed_subscribers;
CREATE POLICY "ofs_admin_all" ON public.opportunity_feed_subscribers
  FOR ALL USING (public.is_site_admin());

-- ----- site_admins -----
DROP POLICY IF EXISTS "sa_admin_read" ON public.site_admins;
CREATE POLICY "sa_admin_read" ON public.site_admins
  FOR SELECT USING (auth.uid() = user_id);

-- ==================== RPC: Publication planifiée ====================

CREATE OR REPLACE FUNCTION public.process_due_scheduled_opportunity_posts()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  _now TIMESTAMPTZ := now();
  _row RECORD;
BEGIN
  FOR _row IN
    SELECT id FROM public.opportunity_posts
    WHERE status = 'scheduled'
      AND scheduled_for IS NOT NULL
      AND scheduled_for <= _now
  LOOP
    UPDATE public.opportunity_posts
    SET status = 'published',
        published_at = COALESCE(published_at, _now),
        updated_at = _now
    WHERE id = _row.id;

    INSERT INTO public.opportunity_post_history (post_id, event_type, detail_json, created_at)
    VALUES (_row.id, 'auto_published', json_build_object('at', _now)::text, _now);
  END LOOP;
END;
$$;

-- ==================== RPC: Recherche publique ====================

CREATE OR REPLACE FUNCTION public.site_search_public(p_query TEXT, p_limit INTEGER DEFAULT 20)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
STABLE
AS $$
DECLARE
  _q TEXT;
  _pattern TEXT;
  _cap INTEGER;
  _per_bucket INTEGER;
  _results JSONB := '[]'::jsonb;
  _row RECORD;
BEGIN
  _q := trim(COALESCE(p_query, ''));
  IF _q = '' THEN
    RETURN jsonb_build_object('query', '', 'results', '[]'::jsonb);
  END IF;
  IF length(_q) > 200 THEN
    RAISE EXCEPTION 'QUERY_TOO_LONG';
  END IF;

  _cap := LEAST(50, GREATEST(1, COALESCE(p_limit, 20)));
  _per_bucket := GREATEST(5, (_cap + 1) / 2);
  _pattern := '%' || replace(replace(replace(lower(_q), '\', '\\'), '%', '\%'), '_', '\_') || '%';

  -- Réalisations publiées
  FOR _row IN
    SELECT id, title, description, category
    FROM public.realisations
    WHERE published = true
      AND (lower(title) LIKE _pattern OR lower(description) LIKE _pattern OR lower(category) LIKE _pattern)
    ORDER BY sort_order ASC, id ASC
    LIMIT _per_bucket
  LOOP
    _results := _results || jsonb_build_object(
      'type', 'realisation',
      'id', _row.id,
      'title', _row.title,
      'excerpt', left(regexp_replace(_row.description, '\s+', ' ', 'g'), 160),
      'href', '/nos-realisations',
      'meta', _row.category
    );
  END LOOP;

  -- Publications opportunités publiées
  FOR _row IN
    SELECT id, category, title, summary, body
    FROM public.opportunity_posts
    WHERE status = 'published'
      AND (
        lower(title) LIKE _pattern
        OR lower(COALESCE(summary, '')) LIKE _pattern
        OR lower(COALESCE(body, '')) LIKE _pattern
        OR lower(COALESCE(organisme, '')) LIKE _pattern
        OR lower(COALESCE(lieu, '')) LIKE _pattern
      )
    ORDER BY COALESCE(published_at, updated_at) DESC, id DESC
    LIMIT _per_bucket
  LOOP
    _results := _results || jsonb_build_object(
      'type', 'opportunity_post',
      'id', _row.id,
      'title', _row.title,
      'excerpt', left(regexp_replace(COALESCE(NULLIF(_row.summary, ''), _row.body, ''), '\s+', ' ', 'g'), 160),
      'href', '/opportunite/' || _row.id,
      'meta', replace(_row.category, '-', ' ')
    );
  END LOOP;

  -- Expertises publiées
  FOR _row IN
    SELECT slug, content_json
    FROM public.service_publications
    WHERE published = true
      AND (lower(slug) LIKE _pattern OR lower(COALESCE(content_json, '')) LIKE _pattern)
    ORDER BY sort_order ASC, slug ASC
    LIMIT _per_bucket
  LOOP
    _results := _results || jsonb_build_object(
      'type', 'expertise',
      'id', _row.slug,
      'title', _row.slug,
      'excerpt', left(_row.slug, 160),
      'href', '/expertises/' || _row.slug,
      'meta', 'Expertise'
    );
  END LOOP;

  RETURN jsonb_build_object('query', _q, 'results', _results);
END;
$$;

-- ==================== Seed service_publications ====================

INSERT INTO public.service_publications (slug, published, sort_order, updated_at)
VALUES
  ('marches-publics', true, 0, now()),
  ('projets', true, 1, now()),
  ('financements-subventions', true, 2, now()),
  ('gouvernance-structuration', true, 3, now()),
  ('optimisation-fiscale', true, 4, now()),
  ('audit-conformite', true, 5, now()),
  ('contentieux-publics', true, 6, now()),
  ('formation-recherche', true, 7, now())
ON CONFLICT (slug) DO NOTHING;

-- ==================== Storage bucket ====================
-- Note: le bucket admin-media doit être créé manuellement dans le dashboard
-- ou via le script apply-migration.mjs
